version: '3.0' #Docker compose version

services:
  angular:
    build: client/e-commerce-client
    ports:
      - "4200:4200"
  express:
    build: backend/e-commerce-client
    ports:
      - "3000:3000"
    links: 
      - database 
  database:
    image: mongo
    ports: 
      - "27017:27017"
    